angular.module('webMenu')

.service('Foods', function(){
	var allfoods = [
		{name:'Butter Chicken',
			id: 0,
			price: 7.99,
			current_size:"Regular",
			sizes: [
				{portion:"Small", sizeprice:5.99, combosizeprice: 6.99},
				{portion:"Regular", sizeprice:6.99, combosizeprice: 7.99},
				{portion:"Large", sizeprice:7.99, combosizeprice: 8.99},
				{portion:"XLarge", sizeprice:8.99, combosizeprice: 9.99}],
			veggie: false,
			imageUrl: 'http://www.akbarsown.com/wp-content/uploads/2015/05/butter-chicken-1.jpg',
			description: 'Delicious butter chicken marinated in an authentic Indian sauce from Uttar Pradesh province. Enjoy with a side of rice and salad.',
			onsale: false,
			combo: true,
			no_negatives: true,
			halal: true,
			max_drinks: 1,
			max_sides: 1,
			max_toppings: 3,
			drinks: [],
			sides: [],
			toppings: [],
			addons: []},
		{name:'Kebab & Rice',
			id: 1,
			price: 8.99,
			current_size:"Regular",
			sizes: [
				{portion:"Small", sizeprice:6.99, combosizeprice: 7.99},
				{portion:"Regular", sizeprice:7.99, combosizeprice: 8.99},
				{portion:"Large", sizeprice:8.99, combosizeprice: 9.99},
				{portion:"XLarge", sizeprice:9.99, combosizeprice: 10.99}],
			veggie: false,
			imageUrl: 'http://www.globeholidays.net/Africa/Egypt/Lower_Egypt/Media/Cairo_Kebab_5.jpg',
			description: 'Kebab is delicious and kebab is nutricious. Sure its just meat on a stick but it tastes so good. Enjoy with a side of rice and salad.',
			onsale: false,
			combo: true,
			no_negatives: true,
			halal: true,
			max_drinks: 1,
			max_sides: 1,
			max_toppings: 3,
			drinks: [],
			sides: [],
			toppings: [],
			addons: []},
		{name:'Tiki Masala',
			id: 2,
			price: 7.99,
			current_size:"Regular",
			sizes: [
				{portion:"Small", sizeprice:5.99, combosizeprice: 6.99},
				{portion:"Regular", sizeprice:6.99, combosizeprice: 7.99},
				{portion:"Large", sizeprice:7.99, combosizeprice: 8.99},
				{portion:"XLarge", sizeprice:8.99, combosizeprice: 9.99}],
			veggie: false,
			imageUrl: 'http://www.tablefortwoblog.com/wp-content/uploads/2012/01/chicken-tikka-masala.jpg',
			description: 'Tiki Masala is a real treat for people who dont eat much ethnic food. I personally dont know what it is but Ill know when I see picture.',
			onsale: false,
			combo: true,
			no_negatives: true,
			halal: true,
			max_drinks: 1,
			max_sides: 1,
			max_toppings: 3,
			drinks: [],
			sides: [],
			toppings: [],
			addons: []},
		{name:'Fish Curry',
			id: 3,
			price: 9.99,
			current_size:"Regular",
			sizes: [
				{portion:"Small", sizeprice:7.99, combosizeprice: 8.99},
				{portion:"Regular", sizeprice:8.99, combosizeprice: 9.99},
				{portion:"Large", sizeprice:9.99, combosizeprice: 10.99},
				{portion:"XLarge", sizeprice:10.99, combosizeprice: 11.99}],
			veggie: false,
			imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Fish_Curry.JPG/1024px-Fish_Curry.JPG',
			description: 'Fish curry is so good you dont understand. I catch my own fish but you can buy local fresh. Enjoy with a side of rice and salad.',
			onsale: false,
			combo: true,
			no_negatives: true,
			halal: true,
			max_drinks: 1,
			max_sides: 1,
			max_toppings: 3,
			drinks: [],
			sides: [],
			toppings: [],
			addons: []},
		{name:'Tandoori Chicken',
			id: 4,
			price: 7.99,
			current_size:"Regular",
			sizes: [
				{portion:"Small", sizeprice:5.99, combosizeprice: 6.99},
				{portion:"Regular", sizeprice:6.99, combosizeprice: 7.99},
				{portion:"Large", sizeprice:7.99, combosizeprice: 8.99},
				{portion:"XLarge", sizeprice:8.99, combosizeprice: 9.99}],
			veggie: false,
			imageUrl: 'http://www.silverspoononline.com/wp-content/uploads/2013/06/sv.jpg',
			description: 'Tandoori chicken, the infamous and delicious. This is like the brown version of Kung Pow Chicken. Enjoy with a side of rice and salad.',
			onsale: false,
			combo: true,
			no_negatives: true,
			halal: true,
			max_drinks: 1,
			max_sides: 1,
			max_toppings: 3,
			drinks: [],
			sides: [],
			toppings: [],
			addons: []},
		{name:'Falafel',
			id: 5,
			price: 6.99,
			current_size:"Regular",
			sizes: [
				{portion:"Small", sizeprice:4.99, combosizeprice: 5.99},
				{portion:"Regular", sizeprice:5.99, combosizeprice: 6.99},
				{portion:"Large", sizeprice:6.99, combosizeprice: 7.99},
				{portion:"XLarge", sizeprice:7.99, combosizeprice: 8.99}],
			veggie: true,
			imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Falafel_balls.jpg',
			description: 'Falafel is like a meatball but its made of chick peas- no meat. Deep fry for a golden bite of hearty goodness. Wrap it up in Shwarama style.',
			onsale: false,
			combo: true,
			no_negatives: true,
			halal: true,
			max_drinks: 1,
			max_sides: 1,
			max_toppings: 3,
			drinks: [],
			sides: [],
			toppings: [],
			addons: []},
		{name:'Goat Leg & Rice',
			id: 6,
			price: 9.99,
			current_size:"Regular",
			sizes: [
				{portion:"Small", sizeprice:7.99, combosizeprice: 8.99},
				{portion:"Regular", sizeprice:8.99, combosizeprice: 9.99},
				{portion:"Large", sizeprice:9.99, combosizeprice: 10.99},
				{portion:"XLarge", sizeprice:10.99, combosizeprice: 11.99}],
			veggie: false,
			imageUrl: 'http://www.greatcurryrecipes.net/wp-content/uploads/2013/02/goat1.jpg',
			description: 'Goat Leg curry served with a generous heaping of rice. Those little carb sticks just soak up that delicious curry. Enjoy with a side of rice and salad.',
			onsale: false,
			combo: true,
			no_negatives: true,
			halal: true,
			max_drinks: 1,
			max_sides: 1,
			max_toppings: 3,
			drinks: [],
			sides: [],
			toppings: [],
			addons: []},
		{name:'Shwarama & Fries',
			id: 7,
			price: 8.99,
			current_size:"Regular",
			sizes: [
				{portion:"Small", sizeprice:6.99, combosizeprice: 7.99},
				{portion:"Regular", sizeprice:7.99, combosizeprice: 8.99},
				{portion:"Large", sizeprice:8.99, combosizeprice: 9.99},
				{portion:"XLarge", sizeprice:9.99, combosizeprice: 10.99}],
			veggie: false,
			imageUrl: 'http://www.mezzalebanesekitchen.ca/img/photo/Shawarma%20Wrap%20%20Fries.jpg',
			description: 'Classic! Shwarama is my to-go food if I want some deep rich meaty taste with fresh veggies and aromatic middle eastern sauces. Im so hungry right now.',
			onsale: false,
			combo: true,
			no_negatives: true,
			halal: true,
			max_drinks: 1,
			max_sides: 1,
			max_toppings: 3,
			drinks: [],
			sides: [],
			toppings: [],
			addons: []},
		{name:'Spicy Seafood Salad',
			id: 8,
			price: 10.99,
			current_size:"Regular",
			sizes: [
				{portion:"Small", sizeprice:8.99, combosizeprice: 9.99},
				{portion:"Regular", sizeprice:9.99, combosizeprice: 10.99},
				{portion:"Large", sizeprice:10.99, combosizeprice: 11.99},
				{portion:"XLarge", sizeprice:11.99, combosizeprice: 12.99}],
			veggie: false,
			imageUrl: 'https://lh3.googleusercontent.com/RBOLDJ8qoZ--Vv7D7i9yevw24C5XBQxBnDK8C8nIRiHz7Choqt-PGbyq8vyHipP89Igbq1P7ttdbY7a2Zcv8j5joDaCI4FMovq1G3F7HPqHcPjHGrod7P3tcVQ',
			description: 'Now this is something you dont see often. Delicious fresh shrimp, surf clam, tipilia fillet and calamari soaked over a bed of veggies.',
			onsale: false,
			combo: true,
			no_negatives: true,
			halal: true,
			max_drinks: 1,
			max_sides: 1,
			max_toppings: 3,
			drinks: [],
			sides: [],
			toppings: [],
			addons: []},
		{name:'Pizza',
			id: 9,
			price: 6.99,
			current_size:"Regular",
			sizes: [
				{portion:"Small", sizeprice:4.99, combosizeprice: 5.99},
				{portion:"Regular", sizeprice:5.99, combosizeprice: 6.99},
				{portion:"Large", sizeprice:6.99, combosizeprice: 7.99},
				{portion:"XLarge", sizeprice:7.99, combosizeprice: 8.99}],
			veggie: false,
			imageUrl: 'http://www.silviocicchi.com/pizzachef/wp-content/uploads/2015/02/p3.jpeg',
			description: 'Classic pizza with all the basics: cheese, tomato sauce and a variety of toppings.',
			onsale: false,
			combo: true,
			no_negatives: true,
			halal: true,
			max_drinks: 1,
			max_sides: 1,
			max_toppings: 1,
			drinks: [],
			sides: [],
			toppings: [],
			addons: []},
		{name:'8pc Bucket of Chicken',
			id: 10,
			price: 12.99,
			current_size:"Regular",
			sizes: [
				{portion:"Small 6pc", sizeprice:8.99, combosizeprice: 10.99},
				{portion:"Regular 8pc", sizeprice:9.99, combosizeprice: 12.99},
				{portion:"Large 10pc", sizeprice:12.99, combosizeprice: 15.99},
				{portion:"XLarge 12pc", sizeprice:14.99, combosizeprice: 19.99}],
			veggie: false,
			imageUrl: 'http://cdn.sheknows.com/articles/fried-chicken(1).jpg',
			description: 'Southern comfort food, a fresh bucket of Louisiana fried chicken! Mhmm mhmm mhmm!',
			onsale: false,
			combo: true,
			no_negatives: true,
			halal: true,
			max_drinks: 1,
			max_sides: 1,
			max_toppings: 0,
			drinks: [],
			sides: [],
			toppings: [],
			addons: []},
		{name:'12pc Wings',
			id: 11,
			price: 11.99,
			current_size:"Regular",
			sizes: [
				{portion:"Small 8pc", sizeprice:9.99, combosizeprice: 10.99},
				{portion:"Regular 12pc", sizeprice:10.99, combosizeprice: 11.99},
				{portion:"Large 15pc", sizeprice:11.99, combosizeprice: 12.99},
				{portion:"XLarge 20pc", sizeprice:12.99, combosizeprice: 13.99}],
			veggie: false,
			imageUrl: 'http://www.libertyvillagetoronto.com/wp-content/uploads/2012/04/Spicy-Chicken-Wings.jpg',
			description: 'Classic breaded and spiced chicken wings with fresh carrots and celery. Comes with 1 dipping sauce.',
			onsale: false,
			combo: true,
			no_negatives: true,
			halal: true,
			max_drinks: 1,
			max_sides: 1,
			max_toppings: 0,
			drinks: [],
			sides: [],
			toppings: [],
			addons: []}
	];

	return {
		get: function(){
			return allfoods;
		}
	}
});