angular.module('webMenu')

.factory('Foods', function(){
	var allfoods = [
		{name:'Butter Chicken',
			id: 0,
			price: 7.99,
			veggie: false,
			imageUrl: 'http://www.akbarsown.com/wp-content/uploads/2015/05/butter-chicken-1.jpg',
			description: 'Delicious butter chicken marinated in an authentic Indian sauce from Uttar Pradesh province. Enjoy with a side of rice and salad.',
			onsale: false,
			combo: true,
			drinks: [],
			sides: [],
			toppings: []},
		{name:'Kebab & Rice',
			id: 1,
			price: 8.99,
			veggie: false,
			imageUrl: 'http://www.globeholidays.net/Africa/Egypt/Lower_Egypt/Media/Cairo_Kebab_5.jpg',
			description: 'Kebab is delicious and kebab is nutricious. Sure its just meat on a stick but it tastes so good. Enjoy with a side of rice and salad.',
			onsale: false,
			combo: true,
			drinks: [],
			sides: [],
			toppings: []},
		{name:'Tiki Masala',
			id: 2,
			price: 7.99,
			veggie: false,
			imageUrl: 'http://www.tablefortwoblog.com/wp-content/uploads/2012/01/chicken-tikka-masala.jpg',
			description: 'Tiki Masala is a real treat for people who dont eat much ethnic food. I personally dont know what it is but Ill know when I see picture.',
			onsale: false,
			combo: true,
			drinks: [],
			sides: [],
			toppings: []},
		{name:'Fish Curry',
			id: 3,
			price: 9.99,
			veggie: false,
			imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Fish_Curry.JPG/1024px-Fish_Curry.JPG',
			description: 'Fish curry is so good you dont understand. I catch my own fish but you can buy local fresh. Enjoy with a side of rice and salad.',
			onsale: false,
			combo: true,
			drinks: [],
			sides: [],
			toppings: []},
		{name:'Tandoori Chicken',
			id: 4,
			price: 7.99,
			veggie: false,
			imageUrl: 'http://www.silverspoononline.com/wp-content/uploads/2013/06/sv.jpg',
			description: 'Tandoori chicken, the infamous and delicious. This is like the brown version of Kung Pow Chicken. Enjoy with a side of rice and salad.',
			onsale: false,
			combo: true,
			drinks: [],
			sides: [],
			toppings: []},
		{name:'Falafel',
			id: 5,
			price: 6.99,
			veggie: true,
			imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Falafel_balls.jpg',
			description: 'Falafel is like a meatball but its made of chick peas- no meat. Deep fry for a golden bite of hearty goodness. Wrap it up in Shwarama style.',
			onsale: false,
			combo: true,
			drinks: [],
			sides: [],
			toppings: []},
		{name:'Goat Leg & Rice',
			id: 6,
			price: 9.99,
			veggie: false,
			imageUrl: 'http://www.greatcurryrecipes.net/wp-content/uploads/2013/02/goat1.jpg',
			description: 'Goat Leg curry served with a generous heaping of rice. Those little carb sticks just soak up that delicious curry. Enjoy with a side of rice and salad.',
			onsale: false,
			combo: true,
			drinks: [],
			sides: [],
			toppings: []},
		{name:'Shwarama & Fries',
			id: 7,
			price: 8.99,
			veggie: false,
			imageUrl: 'http://www.mezzalebanesekitchen.ca/img/photo/Shawarma%20Wrap%20%20Fries.jpg',
			description: 'Classic! Shwarama is my to-go food if I want some deep rich meaty taste with fresh veggies and aromatic middle eastern sauces. Im so hungry right now.',
			onsale: false,
			combo: true,
			drinks: [],
			sides: [],
			toppings: []},
		{name:'Spicy Seafood Salad',
			id: 8,
			price: 10.99,
			veggie: false,
			imageUrl: 'https://lh3.googleusercontent.com/RBOLDJ8qoZ--Vv7D7i9yevw24C5XBQxBnDK8C8nIRiHz7Choqt-PGbyq8vyHipP89Igbq1P7ttdbY7a2Zcv8j5joDaCI4FMovq1G3F7HPqHcPjHGrod7P3tcVQ',
			description: 'Now this is something you dont see often. Delicious fresh shrimp, surf clam, tipilia fillet and calamari soaked over a bed of veggies.',
			onsale: false,
			combo: true,
			drinks: [],
			sides: [],
			toppings: []}
		];

	return {
		get: function(){
			return allfoods;
		}
	}
});